export const Constants = {
  name: 'እኔ ለእኔ',
  description: 'እኔ ለእኔ',
  version: '1.0',
  email: 'testingotp099@gmail.com',
  website: 'www.እኔለእኔ.com',
  country: 'Ethiopia',
  city: 'Addis Ababa',
  otpExpire: 1,
  otpResend: 2,
  uploadDir: 'uploads',
  phoneRegEx: /^(?:\+251|0)\d{9}$/,
  emailRegEx: /^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$/,
  phone: '910101010',
  password: 'password',
};
